<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b01ed87c-6e42-42cb-9d45-59575c5dc329</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Gateway\Api.Gateway.csproj" />
    <ProjectReference Include="..\Api.WeatherForecast\Api.WeatherForecast.csproj" />
    <ProjectReference Include="..\EasyApp.Server\EasyApp.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
  </ItemGroup>
</Project>
